name: "Build and Release"

on: 
  push:
    tags:
      - "v*.*.*"

env:
  PROJECT_PATH: WPFInvoiceSystem/WPFInvoiceSystem.csproj

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: dotnet setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: dotnet restore ${{ env.PROJECT_PATH }}
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -p:PublishSingleFile=true --no-build
  
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /WPFInvoiceSystem/bin/Release/net7.0-windows/win-x64/publish/WPFInvoiceSystem.exe
            /WPFInvoiceSystem/bin/Release/net7.0-windows/win-x64/publish/appsettings.json